### PR TITLE
fix omnibus git caching erros with erchef

### PR DESCRIPTION
**Pull request by sdelano**
@stevendanna @tylercloke @joedevivo @marcparadise @manderson26 @schisamo

### CODE REVIEW

**Comment by tylercloke** [comment]
Yes pls :+1:

**Comment by stevendanna** [comment]
Looks reasonable to me.

**Comment by schisamo** [comment]
:+1:

**Comment by manderson26** [comment]
:+1:

**Comment by sdelano** [comment]
* [ ] foo
* [ ] bar

**Pull request merged**
