### PR TITLE
Bump chef-gem to 11.18.0.

### PR DESCRIPTION
**Pull request by tylercloke**
[Build](http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/279/downstreambuildview/)

### CODE REVIEW

**Comment by tylercloke** [comment]
Build passes.

**Comment by tylercloke** [comment]
Seems to work.

**Comment by sdelano** [comment]
Can you mention in the changelog and release notes that this removes the yajl deprecation warnings?

**Comment by tylercloke** [comment]
Fixes https://github.com/opscode/chef-server/issues/53

**Comment by darkn3rd** [comment]
I'm still seeing this on Chef Server 12.3 running on Cent OS 7.

**Pull request merged**
